### ISSUE TITLE
error when running get_data_output function

### ISSUE THREAD

**Issue by ChenDepp** [xuelingyi/SLRfinder#1]
@xuelingyi @petrikemppainen 
     hi, when i running get_data_output function, it report error as below:
![image](https://github.com/xuelingyi/SLRfinder/assets/48479509/ad0f2dae-9a2d-4ffc-b81f-80e8834f5275)
   can you tell me how to deal with it?
   waiting for your reply
have a good day

**Comment by xuelingyi** [comment]
Hi ChenDepp, 
Thanks for your message. Looks like the input data_cls is in a different format. How did you generate this input file? Can you send your previous codes and the first 30 or so rows of your data_cls? 
Best,
Ling

**Comment by ChenDepp** [comment]
hi @xuelingyi 
       the data_cls as below:
     ![image](https://github.com/xuelingyi/SLRfinder/assets/48479509/acb161d0-802f-4030-985e-54c174f38f1a)
  I referred to the document you wrote and changed the code to ensure that all chromosomes run together.

**Comment by xuelingyi** [comment]
Hi ChenDepp,
Thanks for the screenshot. Your data_cls file looks right. So I think the error might have occurred when the function calculated parameters and/or summarized data. Basically, this function goes through all your LD clusters (one cluster per row in data_cls) and for each cluster, it summarizes data (e.g., SNPs, chi2) into a data frame. This step is done with mclapply. Then all generated data frames are put together into a list by rbindlist. The error was probably generated by rbindlist. If so, it means that the mclapply function did not return a data.frame for at least one of your clusters.

To debug, I suggest running the codes of this function step by step (you can find them in the SLRfinder_functions.r file) instead of running this function as a whole. After creating the gds file for SNPrelate, you can run lines 56-120 in SLRfinder_functions.r manually (or do a for loop) by changing cl from 1 to nrow(data_cls). My guess is that some LD cluster(s) might have too little data for the calculations (e.g. PCA) and therefore you could not get the proper output data frame. Can you please try a few clusters (e.g., cl from 1 to 20) to see if these codes go through? If not, can you please run the codes on only one cluster (e.g., cl=1 or whichever did not go through) to see which part fails? Please let me know what you find out as that might be something we need to improve in this function. Thanks!

**Comment by ChenDepp** [comment]
@xuelingyi  thanks for your suggestion, i do a for loop(find them in the SLRfinder_functions.r file), it successfully
